sudo: false
language: bash

addons:
    apt:
        packages:
            - svn
env:
    - SHUNIT_HOME="/tmp/shunit2/source/2.1"

before_install:
    - git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
    - svn checkout http://shunit2.googlecode.com/svn/trunk/ /tmp/shunit2
script: /tmp/testrunner/bin/run -c .
